// astro.config.mjs
import { defineConfig } from 'astro/config';

export default defineConfig({
  site: 'https://dixieauto.land',
  trailingSlash: 'always',
  output: 'static',
  // Sitemap is generated by src/pages/sitemap.xml.ts (one canonical /sitemap.xml).
  integrations: [],
  build: {
    inlineStylesheets: 'auto',
  },
});
